name: puma_is
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  fluttertoast: ^8.2.8
  cloud_firestore: ^5.5.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  fl_chart: ^0.69.2
  provider: ^6.1.2
  firebase_storage: ^12.3.7
  intl: ^0.20.1
  flutter_datetime_picker_plus: ^2.2.0
  lottie: ^3.2.0
  animated_splash_screen: ^1.3.0
  flutter_native_splash: ^2.4.3
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/candidates-1.jpg
    - assets/images/candidates-2.jpg
    - assets/images/PUMA_IS_BG.jpg
    - assets/images/logo.png
    - assets/images/temuAlumni.jpeg
    - assets/images/profile_pic.png
    - assets/images/cp.jpg
    - assets/images/vcp.jpg
    - assets/images/logonew.png

  uses-material-design: true
